### ISSUE TITLE
Questions about the audit report

### ISSUE THREAD

**Issue by suxnju** [MetaTrustLabs/GPTScan-Web3Bugs#1]
Thanks for your great work! 
I have a small question about the result. Taking [Report_5](https://github.com/MetaTrustLabs/GPTScan-Web3Bugs/blob/dev/reports/MetaScan_AI_Analyzer_Report_5-LogicBug-Vader%20(StaticFail)%20(1OK-SP)_202308071906.pdf) as an example, GPTSCan reported **9** high-risk issues, but only 1 TP and 3 TN were counted in the [result file](https://github.com/MetaTrustLabs/GPTScan-Web3Bugs/blob/dev/web3bugs_res_temp0_230723.csv), Why?

**Comment by daoyuan14** [comment]
Hi, thanks for your interest in GPTScan.

This case "5 (StaticFail-5)" has the underline static engine failed (Similar to 52; Cannot load falcon instance for file: /opt/local/projects/contracts/dex-v2/pool/VaderPoolV2.sol), which affects the rule of "Insecure LP token value calculation" or "Price Manipulation by AMM", so we cut couting this rule for this case. So 5 - 1 = 4 rules.

Among the 4 rules executed on this case, "No Slippage Limit" and its ground-truth function was succesfully identified, so it was marked as 1 TP. The rest of 3 rules were 3 TN.

Note that in the [paper](https://arxiv.org/pdf/2308.03314.pdf) (page 8), we count TP, TN, FP, FN according the following rules:

> For example, if a project has been tested with five vulnerability types, 
> the sum of all true positives, false positives, true negatives,
> and false negatives for this project should be 5. More specifically,
> TP is the number of true positives. One true positive is counted
> when GPTScan successfully detects a ground-truth vulnerable function for the tested vulnerability type.
> TN is the number of true negatives. One true negative is counted
> when GPTScan correctly does not report any vulnerable function
> for the tested vulnerability type.
> FP is the number of false positives. One false positive is counted
> when GPTScan incorrectly reports one or more vulnerable functions
> for the tested vulnerability type that has no corresponding groundtruth vulnerabilities in the tested project.
> FN is the number of false negatives. One false negative is counted
> when GPTScan fails to detect the ground-truth vulnerable function
> for the tested vulnerability type.

**Comment by suxnju** [comment]
> Hi, thanks for your interest in GPTScan.
> 
> This case "5 (StaticFail-5)" has the underline static engine failed (Similar to 52; Cannot load falcon instance for file: /opt/local/projects/contracts/dex-v2/pool/VaderPoolV2.sol), which affects the rule of "Insecure LP token value calculation" or "Price Manipulation by AMM", so we cut couting this rule for this case. So 5 - 1 = 4 rules.
> 
> Among the 4 rules executed on this case, "No Slippage Limit" and its ground-truth function was succesfully identified, so it was marked as 1 TP. The rest of 3 rules were 3 TN.
> 
> Note that in the [paper](https://arxiv.org/pdf/2308.03314.pdf) (page 8), we count TP, TN, FP, FN according the following rules:
> 
> > For example, if a project has been tested with five vulnerability types,
> > the sum of all true positives, false positives, true negatives,
> > and false negatives for this project should be 5. More specifically,
> > TP is the number of true positives. One true positive is counted
> > when GPTScan successfully detects a ground-truth vulnerable function for the tested vulnerability type.
> > TN is the number of true negatives. One true negative is counted
> > when GPTScan correctly does not report any vulnerable function
> > for the tested vulnerability type.
> > FP is the number of false positives. One false positive is counted
> > when GPTScan incorrectly reports one or more vulnerable functions
> > for the tested vulnerability type that has no corresponding groundtruth vulnerabilities in the tested project.
> > FN is the number of false negatives. One false negative is counted
> > when GPTScan fails to detect the ground-truth vulnerable function
> > for the tested vulnerability type.

Thanks for your reply.

Of the 9 detected exceptions, 8 showed “No Slippage Limit”, does `"No Slippage Limit" and its ground-truth function was succesfully identified` mean that all of the 8 detected exceptions are detected as 1 TP?

![image](https://github.com/MetaTrustLabs/GPTScan-Web3Bugs/assets/19996579/c7891a5f-8994-41cd-834e-622d4f7a9f69)


 I also would like to ask does the “ground truth" are labelled manually is based on Web3Bugs?

**Comment by daoyuan14** [comment]
Yes, TP is counted in this way.
Actually, for this case, there are several ground-truth vulnerable functions, all in the type of ""No Slippage Limit."

Additionally, due to the presentation issue of the GPTScan web service, it would display the vulnerable function and its context as two raw results.

Yes, we manually checked the original Web3Bugs vulnerability reports and cross-checked with GPTScan's output.

**Comment by suxnju** [comment]
I got it. Thank you

> Yes, TP is counted in this way. Actually, for this case, there are several ground-truth vulnerable functions, all in the type of ""No Slippage Limit."
> 
> Additionally, due to the presentation issue of the GPTScan web service, it would display the vulnerable function and its context as two raw results.
> 
> Yes, we manually checked the original Web3Bugs vulnerability reports and cross-checked with GPTScan's output.

Got it, thank you!
